version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing dependencies...
      - mvn install

  pre_build:
    commands:
      - echo Running pre-build steps...

  build:
    commands:
      - echo Build started on `date`
      - mvn package

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'